#!/bin/sh
#
# /etc/rc.d/vsftpd: start/stop vsftpd daemon
#

case $1 in
start)
	setsid /usr/sbin/vsftpd &
	;;
stop)
	killall -q /usr/sbin/vsftpd
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file