#!/bin/sh

export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`

gconftool-2 --makefile-install-rule \
	/usr/etc/gconf/schemas/aisleriot.schemas \
	/usr/etc/gconf/schemas/blackjack.schemas \
	/usr/etc/gconf/schemas/gataxx.schemas \
	/usr/etc/gconf/schemas/glines.schemas \
	/usr/etc/gconf/schemas/gnect.schemas \
	/usr/etc/gconf/schemas/gnibbles.schemas \
	/usr/etc/gconf/schemas/gnobots2.schemas \
	/usr/etc/gconf/schemas/gnome-stones.schemas \
	/usr/etc/gconf/schemas/gnometris.schemas \
	/usr/etc/gconf/schemas/gnomine.schemas \
	/usr/etc/gconf/schemas/gnotravex.schemas \
	/usr/etc/gconf/schemas/gnotski.schemas \
	/usr/etc/gconf/schemas/gtali.schemas \
	/usr/etc/gconf/schemas/iagno.schemas \
	/usr/etc/gconf/schemas/libgnomegames.schemas \
	/usr/etc/gconf/schemas/mahjongg.schemas \
	/usr/etc/gconf/schemas/same-gnome.schemas

# End of file
