#!/bin/sh
#
# /etc/rc.d/kdm: start/stop kde display manager
#

case "$1" in
start)
	export HOME=/root
	cd $HOME
	/usr/bin/kdm
	;;
stop)
	killall /usr/bin/kdm
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "usage: $0 start|stop|restart"
	;;
esac

# End of file
